// seedPlans.js
import mongoose from "mongoose";
import dotenv from "dotenv";
import DataPlan from "./src/models/DataPlan.js";
import CablePlan from "./src/models/CablePlan.js";

dotenv.config();

await mongoose.connect(process.env.MONGO_URI);
console.log("Connected to MongoDB");

// ─── DATA PLANS ──────────────────────────────────────────────────────────────

console.log("Clearing existing DataPlans...");
await DataPlan.deleteMany({});

console.log("Inserting data plans...");
await DataPlan.insertMany([
  // ── MTN (serviceID: mtn-data) ──────────────────────────────────────────
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-10mb-100",
    planName: "MTN 100MB - 24hrs",
    size: "100MB",
    costPrice: 100,
    price: 110,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-50mb-200",
    planName: "MTN 200MB - 2 days",
    size: "200MB",
    costPrice: 200,
    price: 220,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-2-5gb-600",
    planName: "MTN 2.5GB - 2 days",
    size: "2.5GB",
    costPrice: 600,
    price: 650,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-3gb-800",
    planName: "MTN 3GB - 2 days",
    size: "3GB",
    costPrice: 800,
    price: 850,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-100mb-1000",
    planName: "MTN 1.5GB - 30 days",
    size: "1.5GB",
    costPrice: 1000,
    price: 1050,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-3gb-1500",
    planName: "MTN 3GB - 30 days",
    size: "3GB",
    costPrice: 1500,
    price: 1550,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-20hrs-1500",
    planName: "MTN 6GB - 7 days",
    size: "6GB",
    costPrice: 1500,
    price: 1600,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-500mb-2000",
    planName: "MTN 4.5GB - 30 days",
    size: "4.5GB",
    costPrice: 2000,
    price: 2100,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-7gb-2000",
    planName: "MTN 7GB - 7 days",
    size: "7GB",
    costPrice: 2000,
    price: 2100,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-3gb-2500",
    planName: "MTN 6GB - 30 days",
    size: "6GB",
    costPrice: 2500,
    price: 2600,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-data-3000",
    planName: "MTN 8GB - 30 days",
    size: "8GB",
    costPrice: 3000,
    price: 3100,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-1gb-3500",
    planName: "MTN 10GB - 30 days",
    size: "10GB",
    costPrice: 3500,
    price: 3600,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-100hr-5000",
    planName: "MTN 15GB - 30 days",
    size: "15GB",
    costPrice: 5000,
    price: 5200,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-3gb-6000",
    planName: "MTN 20GB - 30 days",
    size: "20GB",
    costPrice: 6000,
    price: 6200,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-40gb-10000",
    planName: "MTN 40GB - 30 days",
    size: "40GB",
    costPrice: 10000,
    price: 10300,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-75gb-15000",
    planName: "MTN 75GB - 30 days",
    size: "75GB",
    costPrice: 15000,
    price: 15500,
  },
  {
    network: "MTN",
    serviceID: "mtn-data",
    planCode: "mtn-110gb-20000",
    planName: "MTN 110GB - 30 days",
    size: "110GB",
    costPrice: 20000,
    price: 20700,
  },

  // ── GLO (serviceID: glo-data) ──────────────────────────────────────────
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo100",
    planName: "Glo 105MB - 2 days",
    size: "105MB",
    costPrice: 100,
    price: 110,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo200",
    planName: "Glo 350MB - 4 days",
    size: "350MB",
    costPrice: 200,
    price: 220,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo500",
    planName: "Glo 1.05GB - 14 days",
    size: "1.05GB",
    costPrice: 500,
    price: 550,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo1000",
    planName: "Glo 2.5GB - 30 days",
    size: "2.5GB",
    costPrice: 1000,
    price: 1050,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo1500",
    planName: "Glo 4.1GB - 30 days",
    size: "4.1GB",
    costPrice: 1500,
    price: 1580,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo2000",
    planName: "Glo 5.8GB - 30 days",
    size: "5.8GB",
    costPrice: 2000,
    price: 2100,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo2500",
    planName: "Glo 7.7GB - 30 days",
    size: "7.7GB",
    costPrice: 2500,
    price: 2600,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo3000",
    planName: "Glo 10GB - 30 days",
    size: "10GB",
    costPrice: 3000,
    price: 3100,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo4000",
    planName: "Glo 13.25GB - 30 days",
    size: "13.25GB",
    costPrice: 4000,
    price: 4150,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo5000",
    planName: "Glo 18.25GB - 30 days",
    size: "18.25GB",
    costPrice: 5000,
    price: 5200,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo8000",
    planName: "Glo 29.5GB - 30 days",
    size: "29.5GB",
    costPrice: 8000,
    price: 8300,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo10000",
    planName: "Glo 50GB - 30 days",
    size: "50GB",
    costPrice: 10000,
    price: 10400,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo15000",
    planName: "Glo 93GB - 30 days",
    size: "93GB",
    costPrice: 15000,
    price: 15600,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo18000",
    planName: "Glo 119GB - 30 days",
    size: "119GB",
    costPrice: 18000,
    price: 18700,
  },
  {
    network: "GLO",
    serviceID: "glo-data",
    planCode: "glo20000",
    planName: "Glo 138GB - 30 days",
    size: "138GB",
    costPrice: 20000,
    price: 20800,
  },

  // ── AIRTEL (serviceID: airtel-data) ────────────────────────────────────
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-50",
    planName: "Airtel 25MB - 1 day",
    size: "25MB",
    costPrice: 50,
    price: 60,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-100",
    planName: "Airtel 75MB - 1 day",
    size: "75MB",
    costPrice: 100,
    price: 110,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-200",
    planName: "Airtel 200MB - 3 days",
    size: "200MB",
    costPrice: 200,
    price: 220,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-300",
    planName: "Airtel 350MB - 7 days",
    size: "350MB",
    costPrice: 300,
    price: 330,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-500",
    planName: "Airtel 750MB - 14 days",
    size: "750MB",
    costPrice: 500,
    price: 550,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-600",
    planName: "Airtel 1GB - 14 days",
    size: "1GB",
    costPrice: 600,
    price: 650,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-1000",
    planName: "Airtel 1.5GB - 30 days",
    size: "1.5GB",
    costPrice: 1000,
    price: 1050,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-1500",
    planName: "Airtel 3GB - 30 days",
    size: "3GB",
    costPrice: 1500,
    price: 1580,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-1500-2",
    planName: "Airtel 6GB - 7 days",
    size: "6GB",
    costPrice: 1500,
    price: 1600,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-2000",
    planName: "Airtel 4.5GB - 30 days",
    size: "4.5GB",
    costPrice: 2000,
    price: 2100,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-3000",
    planName: "Airtel 8GB - 30 days",
    size: "8GB",
    costPrice: 3000,
    price: 3100,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-4000",
    planName: "Airtel 11GB - 30 days",
    size: "11GB",
    costPrice: 4000,
    price: 4150,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-5000",
    planName: "Airtel 15GB - 30 days",
    size: "15GB",
    costPrice: 5000,
    price: 5200,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-6000-30",
    planName: "Airtel 23GB - 30 days",
    size: "23GB",
    costPrice: 6000,
    price: 6250,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-10000",
    planName: "Airtel 40GB - 30 days",
    size: "40GB",
    costPrice: 10000,
    price: 10400,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-15000",
    planName: "Airtel 75GB - 30 days",
    size: "75GB",
    costPrice: 15000,
    price: 15600,
  },
  {
    network: "AIRTEL",
    serviceID: "airtel-data",
    planCode: "airt-20000",
    planName: "Airtel 110GB - 30 days",
    size: "110GB",
    costPrice: 20000,
    price: 20800,
  },

  // ── 9MOBILE (serviceID: etisalat-data) ─────────────────────────────────
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-100",
    planName: "9mobile 100MB - 1 day",
    size: "100MB",
    costPrice: 100,
    price: 110,
  },
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-200",
    planName: "9mobile 650MB - 1 day",
    size: "650MB",
    costPrice: 200,
    price: 220,
  },
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-300",
    planName: "9mobile 1GB + 100MB - 1 day",
    size: "1.1GB",
    costPrice: 300,
    price: 330,
  },
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-500",
    planName: "9mobile 500MB - 30 days",
    size: "500MB",
    costPrice: 500,
    price: 550,
  },
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-1000",
    planName: "9mobile 1.5GB - 30 days",
    size: "1.5GB",
    costPrice: 1000,
    price: 1050,
  },
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-2000",
    planName: "9mobile 4.5GB - 30 days",
    size: "4.5GB",
    costPrice: 2000,
    price: 2100,
  },
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-2500",
    planName: "9mobile 11GB - 30 days",
    size: "11GB",
    costPrice: 2500,
    price: 2600,
  },
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-5000",
    planName: "9mobile 15GB - 30 days",
    size: "15GB",
    costPrice: 5000,
    price: 5200,
  },
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-7000",
    planName: "9mobile 35GB - 30 days",
    size: "35GB",
    costPrice: 7000,
    price: 7300,
  },
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-10000",
    planName: "9mobile 40GB - 30 days",
    size: "40GB",
    costPrice: 10000,
    price: 10400,
  },
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-15000",
    planName: "9mobile 75GB - 30 days",
    size: "75GB",
    costPrice: 15000,
    price: 15600,
  },
  {
    network: "9MOBILE",
    serviceID: "etisalat-data",
    planCode: "eti-20000",
    planName: "9mobile 125GB - 30 days",
    size: "125GB",
    costPrice: 20000,
    price: 20800,
  },
]);
console.log("✅ Data plans inserted");

// ─── CABLE PLANS ─────────────────────────────────────────────────────────────

console.log("Clearing existing CablePlans...");
await CablePlan.deleteMany({});

console.log("Inserting cable plans...");
await CablePlan.insertMany([
  // ── DSTV (serviceID: dstv) ─────────────────────────────────────────────
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv-padi",
    planName: "DStv Padi",
    costPrice: 1850,
    price: 1950,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv-yanga",
    planName: "DStv Yanga",
    costPrice: 2565,
    price: 2700,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv-confam",
    planName: "DStv Confam",
    costPrice: 4615,
    price: 4800,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv79",
    planName: "DStv Compact",
    costPrice: 7900,
    price: 8100,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv7",
    planName: "DStv Compact Plus",
    costPrice: 12400,
    price: 12700,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv3",
    planName: "DStv Premium",
    costPrice: 18400,
    price: 18800,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv6",
    planName: "DStv Asia",
    costPrice: 6200,
    price: 6400,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv9",
    planName: "DStv Premium French",
    costPrice: 25550,
    price: 26100,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv10",
    planName: "DStv Premium Asia",
    costPrice: 20500,
    price: 21000,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv30",
    planName: "DStv Compact + ExtraView",
    costPrice: 10400,
    price: 10700,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv45",
    planName: "DStv Compact Plus + ExtraView",
    costPrice: 14900,
    price: 15300,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv33",
    planName: "DStv Premium + ExtraView",
    costPrice: 20900,
    price: 21400,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv-access-1",
    planName: "DStv Access",
    costPrice: 2000,
    price: 2100,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv-family-1",
    planName: "DStv Family",
    costPrice: 4000,
    price: 4150,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "dstv-mobile-1",
    planName: "DStv Mobile",
    costPrice: 790,
    price: 850,
  },
  {
    provider: "DSTV",
    serviceID: "dstv",
    planCode: "extraview-access",
    planName: "ExtraView Access",
    costPrice: 2500,
    price: 2600,
  },

  // ── GOTV (serviceID: gotv) ─────────────────────────────────────────────
  {
    provider: "GOTV",
    serviceID: "gotv",
    planCode: "gotv-lite",
    planName: "GOtv Lite",
    costPrice: 410,
    price: 450,
  },
  {
    provider: "GOTV",
    serviceID: "gotv",
    planCode: "gotv-jinja",
    planName: "GOtv Jinja",
    costPrice: 1640,
    price: 1720,
  },
  {
    provider: "GOTV",
    serviceID: "gotv",
    planCode: "gotv-jolli",
    planName: "GOtv Jolli",
    costPrice: 2460,
    price: 2560,
  },
  {
    provider: "GOTV",
    serviceID: "gotv",
    planCode: "gotv-max",
    planName: "GOtv Max",
    costPrice: 3600,
    price: 3750,
  },
  {
    provider: "GOTV",
    serviceID: "gotv",
    planCode: "gotv-supa-plus",
    planName: "GOtv Supa Plus",
    costPrice: 15700,
    price: 16100,
  },
  {
    provider: "GOTV",
    serviceID: "gotv",
    planCode: "gotv-lite-3months",
    planName: "GOtv Lite (3 Months)",
    costPrice: 1080,
    price: 1150,
  },
  {
    provider: "GOTV",
    serviceID: "gotv",
    planCode: "gotv-lite-1year",
    planName: "GOtv Lite (1 Year)",
    costPrice: 3180,
    price: 3300,
  },

  // ── STARTIMES (serviceID: startimes) ──────────────────────────────────
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "nova-daily",
    planName: "Startimes Nova - 1 Day",
    costPrice: 90,
    price: 100,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "basic-daily",
    planName: "Startimes Basic - 1 Day",
    costPrice: 160,
    price: 180,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "smart-daily",
    planName: "Startimes Smart - 1 Day",
    costPrice: 200,
    price: 220,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "classic-daily",
    planName: "Startimes Classic - 1 Day",
    costPrice: 320,
    price: 350,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "super-daily",
    planName: "Startimes Super - 1 Day",
    costPrice: 400,
    price: 430,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "nova-weekly",
    planName: "Startimes Nova - 1 Week",
    costPrice: 300,
    price: 330,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "basic-weekly",
    planName: "Startimes Basic - 1 Week",
    costPrice: 600,
    price: 650,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "smart-weekly",
    planName: "Startimes Smart - 1 Week",
    costPrice: 700,
    price: 750,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "classic-weekly",
    planName: "Startimes Classic - 1 Week",
    costPrice: 1200,
    price: 1280,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "super-weekly",
    planName: "Startimes Super - 1 Week",
    costPrice: 1500,
    price: 1600,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "nova",
    planName: "Startimes Nova - 1 Month",
    costPrice: 900,
    price: 970,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "basic",
    planName: "Startimes Basic - 1 Month",
    costPrice: 1700,
    price: 1800,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "smart",
    planName: "Startimes Smart - 1 Month",
    costPrice: 2200,
    price: 2320,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "classic",
    planName: "Startimes Classic - 1 Month",
    costPrice: 2500,
    price: 2620,
  },
  {
    provider: "STARTIMES",
    serviceID: "startimes",
    planCode: "super",
    planName: "Startimes Super - 1 Month",
    costPrice: 4200,
    price: 4400,
  },
]);
console.log("✅ Cable plans inserted");

console.log("Done. Disconnecting...");
await mongoose.disconnect();
