// seedPlans.js
import mongoose from "mongoose";
import dotenv from "dotenv";
import DataPlan from "./src/models/DataPlan.js";
import CablePlan from "./src/models/CablePlan.js";

dotenv.config();

await mongoose.connect(process.env.MONGO_URI);
console.log("Connected to MongoDB");

// ─── DATA PLANS ─────────────────────────────────────────────────────────────

console.log("Clearing existing DataPlans...");
await DataPlan.deleteMany({});

console.log("Inserting data plans...");
await DataPlan.insertMany([
  // ── MTN (serviceID: mtn-data) ──────────────────────────────────────────
  {
    network: "MTN",
    name: "100MB - 24hrs",
    planCode: "mtn-10mb-100",
    serviceID: "mtn-data",
    amount: 100,
  },
  {
    network: "MTN",
    name: "200MB - 2 days",
    planCode: "mtn-50mb-200",
    serviceID: "mtn-data",
    amount: 200,
  },
  {
    network: "MTN",
    name: "2.5GB - 2 days",
    planCode: "mtn-2-5gb-600",
    serviceID: "mtn-data",
    amount: 600,
  },
  {
    network: "MTN",
    name: "3GB - 2 days",
    planCode: "mtn-3gb-800",
    serviceID: "mtn-data",
    amount: 800,
  },
  {
    network: "MTN",
    name: "6GB - 7 days",
    planCode: "mtn-20hrs-1500",
    serviceID: "mtn-data",
    amount: 1500,
  },
  {
    network: "MTN",
    name: "7GB - 7 days",
    planCode: "mtn-7gb-2000",
    serviceID: "mtn-data",
    amount: 2000,
  },
  {
    network: "MTN",
    name: "1.5GB - 30 days",
    planCode: "mtn-100mb-1000",
    serviceID: "mtn-data",
    amount: 1000,
  },
  {
    network: "MTN",
    name: "3GB - 30 days",
    planCode: "mtn-3gb-1500",
    serviceID: "mtn-data",
    amount: 1500,
  },
  {
    network: "MTN",
    name: "4.5GB - 30 days",
    planCode: "mtn-500mb-2000",
    serviceID: "mtn-data",
    amount: 2000,
  },
  {
    network: "MTN",
    name: "6GB - 30 days",
    planCode: "mtn-3gb-2500",
    serviceID: "mtn-data",
    amount: 2500,
  },
  {
    network: "MTN",
    name: "8GB - 30 days",
    planCode: "mtn-data-3000",
    serviceID: "mtn-data",
    amount: 3000,
  },
  {
    network: "MTN",
    name: "10GB - 30 days",
    planCode: "mtn-1gb-3500",
    serviceID: "mtn-data",
    amount: 3500,
  },
  {
    network: "MTN",
    name: "15GB - 30 days",
    planCode: "mtn-100hr-5000",
    serviceID: "mtn-data",
    amount: 5000,
  },
  {
    network: "MTN",
    name: "20GB - 30 days",
    planCode: "mtn-3gb-6000",
    serviceID: "mtn-data",
    amount: 6000,
  },
  {
    network: "MTN",
    name: "40GB - 30 days",
    planCode: "mtn-40gb-10000",
    serviceID: "mtn-data",
    amount: 10000,
  },
  {
    network: "MTN",
    name: "75GB - 30 days",
    planCode: "mtn-75gb-15000",
    serviceID: "mtn-data",
    amount: 15000,
  },
  {
    network: "MTN",
    name: "110GB - 30 days",
    planCode: "mtn-110gb-20000",
    serviceID: "mtn-data",
    amount: 20000,
  },

  // ── GLO (serviceID: glo-data) ──────────────────────────────────────────
  {
    network: "GLO",
    name: "105MB - 2 days",
    planCode: "glo100",
    serviceID: "glo-data",
    amount: 100,
  },
  {
    network: "GLO",
    name: "350MB - 4 days",
    planCode: "glo200",
    serviceID: "glo-data",
    amount: 200,
  },
  {
    network: "GLO",
    name: "1.05GB - 14 days",
    planCode: "glo500",
    serviceID: "glo-data",
    amount: 500,
  },
  {
    network: "GLO",
    name: "2.5GB - 30 days",
    planCode: "glo1000",
    serviceID: "glo-data",
    amount: 1000,
  },
  {
    network: "GLO",
    name: "4.1GB - 30 days",
    planCode: "glo1500",
    serviceID: "glo-data",
    amount: 1500,
  },
  {
    network: "GLO",
    name: "5.8GB - 30 days",
    planCode: "glo2000",
    serviceID: "glo-data",
    amount: 2000,
  },
  {
    network: "GLO",
    name: "7.7GB - 30 days",
    planCode: "glo2500",
    serviceID: "glo-data",
    amount: 2500,
  },
  {
    network: "GLO",
    name: "10GB - 30 days",
    planCode: "glo3000",
    serviceID: "glo-data",
    amount: 3000,
  },
  {
    network: "GLO",
    name: "13.25GB - 30 days",
    planCode: "glo4000",
    serviceID: "glo-data",
    amount: 4000,
  },
  {
    network: "GLO",
    name: "18.25GB - 30 days",
    planCode: "glo5000",
    serviceID: "glo-data",
    amount: 5000,
  },
  {
    network: "GLO",
    name: "29.5GB - 30 days",
    planCode: "glo8000",
    serviceID: "glo-data",
    amount: 8000,
  },
  {
    network: "GLO",
    name: "50GB - 30 days",
    planCode: "glo10000",
    serviceID: "glo-data",
    amount: 10000,
  },
  {
    network: "GLO",
    name: "93GB - 30 days",
    planCode: "glo15000",
    serviceID: "glo-data",
    amount: 15000,
  },
  {
    network: "GLO",
    name: "119GB - 30 days",
    planCode: "glo18000",
    serviceID: "glo-data",
    amount: 18000,
  },
  {
    network: "GLO",
    name: "138GB - 30 days",
    planCode: "glo20000",
    serviceID: "glo-data",
    amount: 20000,
  },

  // ── AIRTEL (serviceID: airtel-data) ────────────────────────────────────
  {
    network: "Airtel",
    name: "25MB - 1 day",
    planCode: "airt-50",
    serviceID: "airtel-data",
    amount: 50,
  },
  {
    network: "Airtel",
    name: "75MB - 1 day",
    planCode: "airt-100",
    serviceID: "airtel-data",
    amount: 100,
  },
  {
    network: "Airtel",
    name: "200MB - 3 days",
    planCode: "airt-200",
    serviceID: "airtel-data",
    amount: 200,
  },
  {
    network: "Airtel",
    name: "350MB - 7 days",
    planCode: "airt-300",
    serviceID: "airtel-data",
    amount: 300,
  },
  {
    network: "Airtel",
    name: "750MB - 14 days",
    planCode: "airt-500",
    serviceID: "airtel-data",
    amount: 500,
  },
  {
    network: "Airtel",
    name: "1GB - 14 days",
    planCode: "airt-600",
    serviceID: "airtel-data",
    amount: 600,
  },
  {
    network: "Airtel",
    name: "1.5GB - 30 days",
    planCode: "airt-1000",
    serviceID: "airtel-data",
    amount: 1000,
  },
  {
    network: "Airtel",
    name: "3GB - 30 days",
    planCode: "airt-1500",
    serviceID: "airtel-data",
    amount: 1500,
  },
  {
    network: "Airtel",
    name: "6GB - 7 days",
    planCode: "airt-1500-2",
    serviceID: "airtel-data",
    amount: 1500,
  },
  {
    network: "Airtel",
    name: "4.5GB - 30 days",
    planCode: "airt-2000",
    serviceID: "airtel-data",
    amount: 2000,
  },
  {
    network: "Airtel",
    name: "8GB - 30 days",
    planCode: "airt-3000",
    serviceID: "airtel-data",
    amount: 3000,
  },
  {
    network: "Airtel",
    name: "11GB - 30 days",
    planCode: "airt-4000",
    serviceID: "airtel-data",
    amount: 4000,
  },
  {
    network: "Airtel",
    name: "15GB - 30 days",
    planCode: "airt-5000",
    serviceID: "airtel-data",
    amount: 5000,
  },
  {
    network: "Airtel",
    name: "23GB - 30 days",
    planCode: "airt-6000-30",
    serviceID: "airtel-data",
    amount: 6000,
  },
  {
    network: "Airtel",
    name: "40GB - 30 days",
    planCode: "airt-10000",
    serviceID: "airtel-data",
    amount: 10000,
  },
  {
    network: "Airtel",
    name: "75GB - 30 days",
    planCode: "airt-15000",
    serviceID: "airtel-data",
    amount: 15000,
  },
  {
    network: "Airtel",
    name: "110GB - 30 days",
    planCode: "airt-20000",
    serviceID: "airtel-data",
    amount: 20000,
  },

  // ── 9MOBILE (serviceID: etisalat-data) ─────────────────────────────────
  {
    network: "9mobile",
    name: "100MB - 1 day",
    planCode: "eti-100",
    serviceID: "etisalat-data",
    amount: 100,
  },
  {
    network: "9mobile",
    name: "650MB - 1 day",
    planCode: "eti-200",
    serviceID: "etisalat-data",
    amount: 200,
  },
  {
    network: "9mobile",
    name: "1GB + 100MB - 1 day",
    planCode: "eti-300",
    serviceID: "etisalat-data",
    amount: 300,
  },
  {
    network: "9mobile",
    name: "500MB - 30 days",
    planCode: "eti-500",
    serviceID: "etisalat-data",
    amount: 500,
  },
  {
    network: "9mobile",
    name: "1.5GB - 30 days",
    planCode: "eti-1000",
    serviceID: "etisalat-data",
    amount: 1000,
  },
  {
    network: "9mobile",
    name: "4.5GB - 30 days",
    planCode: "eti-2000",
    serviceID: "etisalat-data",
    amount: 2000,
  },
  {
    network: "9mobile",
    name: "11GB - 30 days",
    planCode: "eti-2500",
    serviceID: "etisalat-data",
    amount: 2500,
  },
  {
    network: "9mobile",
    name: "15GB - 30 days",
    planCode: "eti-5000",
    serviceID: "etisalat-data",
    amount: 5000,
  },
  {
    network: "9mobile",
    name: "35GB - 30 days",
    planCode: "eti-7000",
    serviceID: "etisalat-data",
    amount: 7000,
  },
  {
    network: "9mobile",
    name: "40GB - 30 days",
    planCode: "eti-10000",
    serviceID: "etisalat-data",
    amount: 10000,
  },
  {
    network: "9mobile",
    name: "75GB - 30 days",
    planCode: "eti-15000",
    serviceID: "etisalat-data",
    amount: 15000,
  },
  {
    network: "9mobile",
    name: "125GB - 30 days",
    planCode: "eti-20000",
    serviceID: "etisalat-data",
    amount: 20000,
  },
]);
console.log("✅ Data plans inserted");

// ─── CABLE PLANS ─────────────────────────────────────────────────────────────

console.log("Clearing existing CablePlans...");
await CablePlan.deleteMany({});

console.log("Inserting cable plans...");
await CablePlan.insertMany([
  // ── DSTV (serviceID: dstv) ─────────────────────────────────────────────
  {
    provider: "DSTV",
    name: "DStv Padi",
    planCode: "dstv-padi",
    serviceID: "dstv",
    amount: 1850,
  },
  {
    provider: "DSTV",
    name: "DStv Yanga",
    planCode: "dstv-yanga",
    serviceID: "dstv",
    amount: 2565,
  },
  {
    provider: "DSTV",
    name: "DStv Confam",
    planCode: "dstv-confam",
    serviceID: "dstv",
    amount: 4615,
  },
  {
    provider: "DSTV",
    name: "DStv Compact",
    planCode: "dstv79",
    serviceID: "dstv",
    amount: 7900,
  },
  {
    provider: "DSTV",
    name: "DStv Compact Plus",
    planCode: "dstv7",
    serviceID: "dstv",
    amount: 12400,
  },
  {
    provider: "DSTV",
    name: "DStv Premium",
    planCode: "dstv3",
    serviceID: "dstv",
    amount: 18400,
  },
  {
    provider: "DSTV",
    name: "DStv Asia",
    planCode: "dstv6",
    serviceID: "dstv",
    amount: 6200,
  },
  {
    provider: "DSTV",
    name: "DStv Premium French",
    planCode: "dstv9",
    serviceID: "dstv",
    amount: 25550,
  },
  {
    provider: "DSTV",
    name: "DStv Premium Asia",
    planCode: "dstv10",
    serviceID: "dstv",
    amount: 20500,
  },
  {
    provider: "DSTV",
    name: "DStv Compact + ExtraView",
    planCode: "dstv30",
    serviceID: "dstv",
    amount: 10400,
  },
  {
    provider: "DSTV",
    name: "DStv Compact Plus + ExtraView",
    planCode: "dstv45",
    serviceID: "dstv",
    amount: 14900,
  },
  {
    provider: "DSTV",
    name: "DStv Premium + ExtraView",
    planCode: "dstv33",
    serviceID: "dstv",
    amount: 20900,
  },
  {
    provider: "DSTV",
    name: "DStv Access",
    planCode: "dstv-access-1",
    serviceID: "dstv",
    amount: 2000,
  },
  {
    provider: "DSTV",
    name: "DStv Family",
    planCode: "dstv-family-1",
    serviceID: "dstv",
    amount: 4000,
  },
  {
    provider: "DSTV",
    name: "DStv Mobile",
    planCode: "dstv-mobile-1",
    serviceID: "dstv",
    amount: 790,
  },
  {
    provider: "DSTV",
    name: "ExtraView Access",
    planCode: "extraview-access",
    serviceID: "dstv",
    amount: 2500,
  },

  // ── GOTV (serviceID: gotv) ─────────────────────────────────────────────
  {
    provider: "GOTV",
    name: "GOtv Lite",
    planCode: "gotv-lite",
    serviceID: "gotv",
    amount: 410,
  },
  {
    provider: "GOTV",
    name: "GOtv Jinja",
    planCode: "gotv-jinja",
    serviceID: "gotv",
    amount: 1640,
  },
  {
    provider: "GOTV",
    name: "GOtv Jolli",
    planCode: "gotv-jolli",
    serviceID: "gotv",
    amount: 2460,
  },
  {
    provider: "GOTV",
    name: "GOtv Max",
    planCode: "gotv-max",
    serviceID: "gotv",
    amount: 3600,
  },
  {
    provider: "GOTV",
    name: "GOtv Supa Plus",
    planCode: "gotv-supa-plus",
    serviceID: "gotv",
    amount: 15700,
  },
  {
    provider: "GOTV",
    name: "GOtv Lite (3 Months)",
    planCode: "gotv-lite-3months",
    serviceID: "gotv",
    amount: 1080,
  },
  {
    provider: "GOTV",
    name: "GOtv Lite (1 Year)",
    planCode: "gotv-lite-1year",
    serviceID: "gotv",
    amount: 3180,
  },

  // ── STARTIMES (serviceID: startimes) ──────────────────────────────────
  {
    provider: "Startimes",
    name: "Nova - 1 Day",
    planCode: "nova-daily",
    serviceID: "startimes",
    amount: 90,
  },
  {
    provider: "Startimes",
    name: "Basic - 1 Day",
    planCode: "basic-daily",
    serviceID: "startimes",
    amount: 160,
  },
  {
    provider: "Startimes",
    name: "Smart - 1 Day",
    planCode: "smart-daily",
    serviceID: "startimes",
    amount: 200,
  },
  {
    provider: "Startimes",
    name: "Classic - 1 Day",
    planCode: "classic-daily",
    serviceID: "startimes",
    amount: 320,
  },
  {
    provider: "Startimes",
    name: "Super - 1 Day",
    planCode: "super-daily",
    serviceID: "startimes",
    amount: 400,
  },
  {
    provider: "Startimes",
    name: "Nova - 1 Week",
    planCode: "nova-weekly",
    serviceID: "startimes",
    amount: 300,
  },
  {
    provider: "Startimes",
    name: "Basic - 1 Week",
    planCode: "basic-weekly",
    serviceID: "startimes",
    amount: 600,
  },
  {
    provider: "Startimes",
    name: "Smart - 1 Week",
    planCode: "smart-weekly",
    serviceID: "startimes",
    amount: 700,
  },
  {
    provider: "Startimes",
    name: "Classic - 1 Week",
    planCode: "classic-weekly",
    serviceID: "startimes",
    amount: 1200,
  },
  {
    provider: "Startimes",
    name: "Super - 1 Week",
    planCode: "super-weekly",
    serviceID: "startimes",
    amount: 1500,
  },
  {
    provider: "Startimes",
    name: "Nova - 1 Month",
    planCode: "nova",
    serviceID: "startimes",
    amount: 900,
  },
  {
    provider: "Startimes",
    name: "Basic - 1 Month",
    planCode: "basic",
    serviceID: "startimes",
    amount: 1700,
  },
  {
    provider: "Startimes",
    name: "Smart - 1 Month",
    planCode: "smart",
    serviceID: "startimes",
    amount: 2200,
  },
  {
    provider: "Startimes",
    name: "Classic - 1 Month",
    planCode: "classic",
    serviceID: "startimes",
    amount: 2500,
  },
  {
    provider: "Startimes",
    name: "Super - 1 Month",
    planCode: "super",
    serviceID: "startimes",
    amount: 4200,
  },
]);
console.log("✅ Cable plans inserted");

console.log("Done. Disconnecting...");
await mongoose.disconnect();
